### PR TITLE
thumb detail fallback

### PR DESCRIPTION
**Pull request by primaeval**
Hi. Someone asked me to fix this addon for them. This seems to work in Krypton so far. Thanks.

### CODE REVIEW

**Comment by Norin-Radd** [comment]
sure, go ahead iam not a dev ;)

**Comment by primaeval** [comment]
nice addon by the way.
I'm just watching the JamieXX Live stream. Top tunes. ;)

**Comment by Norin-Radd** [comment]
credits are for enen92, its is code, i only changed the channel id, i just thought it was good content. Iam glad that people enjoy it.

:) have fun

**Comment by primaeval** [comment]
Is it in a repo somewhere?

**Comment by Norin-Radd** [comment]
yes, one of my addons is a fork from the official repo, but it's for another youtube channel, it´s a copy of the kordkutters addon

**Comment by Norin-Radd** [comment]
it´s here https://github.com/enen92/plugin.video.kordkutters

in case you haven´t noticed i don´t know how to work in github eheheh

cheers

**Comment by primaeval** [comment]
I've added it to my kodi repo at the moment so it is easy to install. I hope you don't mind.
https://github.com/primaeval/repository.primaeval

**Pull request merged**
